### ISSUE TITLE
vue3 通用模板版本  自定义选择 报错

### ISSUE THREAD

**Issue by liweijie0812** [Tencent/tdesign-starter-cli#38]
### tdesign-starter-cli 版本

v0.3.2

### 重现步骤

✔ 构建环境正常！

? 请输入项目名称： aa
? 请输入项目描述： Base on tdesign-starter-cli
? 选择模板类型： 【Vue3】模板
? 生成代码版本：  通用模板版本
? 选择包含模块： 自定义选择

### 实际结果

TypeError: Cannot read properties of undefined (reading 'replace')
    at e.generateSourceModulesData (C:\Users\LI\AppData\Roaming\npm\node_modules\tdesign-starter-cli\bin\index.js:2:11248)
    at e.parseConfigSourceVue3 (C:\Users\LI\AppData\Roaming\npm\node_modules\tdesign-starter-cli\bin\index.js:2:26617)
    at e.<anonymous> (C:\Users\LI\AppData\Roaming\npm\node_modules\tdesign-starter-cli\bin\index.js:2:24821)
    at step (C:\Users\LI\AppData\Roaming\npm\node_modules\tdesign-starter-cli\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\LI\AppData\Roaming\npm\node_modules\tdesign-starter-cli\node_modules\tslib\tslib.js:124:57)
    at fulfilled (C:\Users\LI\AppData\Roaming\npm\node_modules\tdesign-starter-cli\node_modules\tslib\tslib.js:114:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### 系统版本

win11

### Node版本

v18.14.0

**Comment by uyarn** [comment]
fixed 0.3.3
